export { About } from './About'
export { Contacts } from './Contacts'
export { FAQ } from './FAQ'
export { Home } from './Home'
export { NotFound } from './NotFound'
export { OrderForm } from './OrderForm'
export { Suppliers } from './Suppliers'
